### ISSUE TITLE
Bot doesn't join all raffle

### ISSUE THREAD

**Issue by Powtaitoe** [iraizo/scraptf-py#1]
Bot seems to join half only. Out of 200 public raffles, only 100 is joined before the terminal says all raffles join despite there being 100 unjoined raffles still active.

**Comment by iraizo** [comment]
will investigate this today

**Comment by Powtaitoe** [comment]
![Capture](https://user-images.githubusercontent.com/61673615/75993929-2e205e00-5f35-11ea-9380-ded27321c370.PNG)
![Capture 1](https://user-images.githubusercontent.com/61673615/75993988-44c6b500-5f35-11ea-8b58-c7a968c44e2c.PNG)

**Comment by iraizo** [comment]
Youre supposed to run it once
